name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Src/Campus.Master.API/Campus.Master.API.sln
    - name: Build
      run: dotnet build Src/Campus.Master.API/Campus.Master.API.sln --configuration Release --no-restore
