name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Angular via Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Install Packages
      run: npm install --prefix UI/Campus-UI
    - name: Lint UI
      run: npm run lint:ci --prefix UI/Campus-UI
    - name: Build UI
      run: npm run build:ci --prefix UI/Campus-UI
    - name: Build UI Production
      run: npm run build:ci:prod --prefix UI/Campus-UI    
